openapi: 3.1.0
info:
  title: Rust app
  version: 0.1.0
paths:
  /:
    get:
      summary: Return Hello, World
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, World!"
