apiVersion: v1
kind: Service
metadata:
  name: rustapp-service
spec:
  selector:
    app: rustapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000  # Port the container is listening on
  type: LoadBalancer  # Use LoadBalancer for external access
